import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  brainBuilder: [
    "intro",
    {
      type: "category",
      label: "Brain Visualizer",
      // Pages synced from feagi/brain-visualizer at build time
      items: [{ type: "autogenerated", dirName: "visualizer" }],
    },
  ],
};

export default sidebars;
