import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  contributing: [
    "intro",
    {
      type: "category",
      label: "Architecture & Design Docs",
      // Docs synced from feagi/feagi-core at build time
      items: [{ type: "autogenerated", dirName: "feagi-core-source" }],
    },
  ],
};

export default sidebars;
