import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  sdk: [
    "index",
    {
      type: "category",
      label: "Embodiment Connectors",
      // READMEs synced from feagi/embodiment-controllers at build time
      items: [{ type: "autogenerated", dirName: "embodiments" }],
    },
  ],
};

export default sidebars;
